### ISSUE TITLE
vmaBuildStatsString compilation errors with older Vulkan SDK

### ISSUE THREAD

**Issue by csisy** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#261]
Hello,

Just updated to the latest version on the master and by default the `VMA_STATS_STRING_ENABLED` is set to `1`.

In this case the `vmaBuildStatsString` does not compile:, it cannot find `VK_API_VERSION_{MAJOR|MINOR|PATCH}`:

```
VulkanMemoryAllocator\include\vk_mem_alloc.h(16155): error C3861: 'VK_API_VERSION_MAJOR': identifier not found
VulkanMemoryAllocator\include\vk_mem_alloc.h(16157): error C3861: 'VK_API_VERSION_MINOR': identifier not found
VulkanMemoryAllocator\include\vk_mem_alloc.h(16159): error C3861: 'VK_API_VERSION_PATCH': identifier not found
```

This happens in the cpp file where the `VMA_IMPLEMENTATION` is defined. Using (latest) MSVC.

However, it seems that my Vulkan SDK is older than it should be, so the `VK_API_VERSION_MAJOR` is not defined in the `vulkan_core.h` (just the deprecated `VK_VERSION_MAJOR`).

---

**Edit**

Confirmed, working with the latest Vulkan SDK.

**Comment by adam-sawicki-a** [comment]
I'm happy to hear it eventually worked for you. VMA is designed to work with Vulkan version down to 1.0, but identifiers like `VK_API_VERSION_MAJOR` should be defined by Vulkan headers in all of them.

**Comment by taril42** [comment]
For what it's worth: we had the same issue; our macOS and Linux versions of the VulkanSDK lag a little behind our Windows ones (1.2 vs 1.3):

VulkanSDK 1.2.162.1 for Linux.
VulkanSDK 1.2.189.0 for macOS.

Those two didn't work, while our Windows side:

VulkanSDK 1.3.211.0 for Windows
 
...worked fine.  All of these were downloaded from sdk.lunarg.com .

Our workaround was this block in our VMA_IMPLEMENTATION file, until I can get around to upgrading:

```
/* Minor backcompat fix (we're still using VulkanSDK 1.2 on macOS/linux. Can be dropped when >= SDK 1.3 */
#ifndef VK_API_VERSION_VARIANT
#define VK_API_VERSION_VARIANT(version) ((uint32_t)(version) >> 29)
#endif
#ifndef VK_API_VERSION_MAJOR
#define VK_API_VERSION_MAJOR(version) (((uint32_t)(version) >> 22) & 0x7FU)
#endif
#ifndef VK_API_VERSION_MINOR
#define VK_API_VERSION_MINOR(version) (((uint32_t)(version) >> 12) & 0x3FFU)
#endif
#ifndef VK_API_VERSION_PATCH
#define VK_API_VERSION_PATCH(version) ((uint32_t)(version) & 0xFFFU)
#endif
```
