### ISSUE TITLE
Unable to build on Clang 8.0.0

### ISSUE THREAD

**Issue by phoekz** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#71]
```
In file included from src/p3d-vma.cpp:9:                                                                                                                                           
ext/VulkanMemoryAllocator/src\vk_mem_alloc.h:4441:47: error: call to implicitly-deleted default constructor of 'VmaPoolAllocator<VmaAllocation_T>::Item'                           
        vma_new_array(m_pAllocationCallbacks, Item, newBlockCapacity),                                                                                                             
                                              ^                                                                                                                                    
ext/VulkanMemoryAllocator/src\vk_mem_alloc.h:4404:27: note: in instantiation of member function 'VmaPoolAllocator<VmaAllocation_T>::CreateNewBlock' requested here                 
    ItemBlock& newBlock = CreateNewBlock();                                                                                                                                        
                          ^                                                                                                                                                        
ext/VulkanMemoryAllocator/src\vk_mem_alloc.h:14113:24: note: in instantiation of member function 'VmaPoolAllocator<VmaAllocation_T>::Alloc' requested here                         
    return m_Allocator.Alloc();                                                                                                                                                    
                       ^                                                                                                                                                           
ext/VulkanMemoryAllocator/src\vk_mem_alloc.h:4348:11: note: default constructor of 'Item' is implicitly deleted because variant field 'Value' has a non-trivial default constructor
        T Value;                                                                                                                                                                   
          ^                                                                                                                                                                        
1 error generated.       
```

I am not exactly sure what is going on, but I suspect the error is caused by the member `VmaAllocation_T::m_LastUseFrameIndex;` Its type is `std::atomic<uint32_t>` which does have a constructor. `VmaPoolAllocator` places one of those inside an union.

My build command is:
```
$ clang++.exe src/p3d-vma.cpp -Iinclude -Iext/VulkanMemoryAllocator/src -Iext/Vulkan-1.1.97.0/include
```

Contents of `p3d-vma.cpp`:

```
#define VMA_IMPLEMENTATION
#include <vk_mem_alloc.h>
```

`clang++ --version`:

```
$ clang++.exe --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by adam-sawicki-amd** [comment]
Thank you for reporting this issue. Indeed it looks like there is a bug as you described, which may occur in some compiler environments. I will work on a fix.

**Comment by adam-sawicki-amd** [comment]
I've submitted a potential fix to master branch. Please let me know if it solves the problem on your platform.

**Comment by phoekz** [comment]
Awesome, the latest commit did solve the problem!

**Comment by adam-sawicki-amd** [comment]
Great, thanks!
